### ISSUE TITLE
Not reloading after setting up amari token

### ISSUE THREAD

**Issue by japandotorg** [i-am-zaidali/cray-cogs#16]
```py
Exception during loading of package
Traceback (most recent call last):
  File "/home/opc/env/lib64/python3.9/site-packages/redbot/core/core_commands.py", line 172, in _load
    await bot.load_extension(spec)
  File "/home/opc/env/lib64/python3.9/site-packages/redbot/core/bot.py", line 1561, in load_extension
    await lib.setup(self)
  File "/home/opc/.local/share/Red-DiscordBot/data/esdeath/cogs/esdeath/giveaways/__init__.py", line 11, in setup
    bot.add_cog(await giveaways.inititalze(bot))
  File "/home/opc/.local/share/Red-DiscordBot/data/esdeath/cogs/esdeath/giveaways/events.py", line 43, in inititalze
    amari = AmariClient(bot, auth)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by i-am-zaidali** [comment]
ok so after extensive testing, I can't seem to recreate this error in anyway. Also this doesn't seem to be the whole traceback. it would help if u would show that.

**Comment by japandotorg** [comment]
Apparently this is happening in my vps only ig, i tried to make another instance for giveaways specifically but yeah got the same-ish error with Amari?

**Comment by i-am-zaidali** [comment]
@japandotorg so i have rewritten the whole cog and merged the changes. You can update the cog and check it out, that error shouldn't come up anymore hopefully

**Comment by japandotorg** [comment]
![this](https://user-images.githubusercontent.com/78662983/152950177-856cb6dc-97a0-4b7d-aec9-0c8bf488d8f3.png)

output of pip freeze, btw thanks for the rewrite, will it glitch the old giveaways tho?

**Comment by japandotorg** [comment]
f closed my mistake

**Comment by japandotorg** [comment]
jeez my ip was literally on the last ss i commented
![Screenshot 2022-02-08 141605](https://user-images.githubusercontent.com/78662983/152950545-e27e0a32-523f-477a-901e-9024c2f3ebdd.png)
the the output of pip freeze, btw will it glitch/yeet the old giveaways i hosted tho?

**Comment by i-am-zaidali** [comment]
No problemo. Glad to see that you liked it :D
