### ISSUE TITLE
[giveaway] Do not accept None as Amari API token

### ISSUE THREAD

**Issue by Artemis6969** [i-am-zaidali/cray-cogs#23]
Running "[p]set api amari auth, "  Deletes the message and returns Api key set instead of telling the user to input a valid token

**Comment by Artemis6969** [comment]
Yes, There is a space after the ,

**Comment by i-am-zaidali** [comment]
Just simply don't set a token. Its totally optional and the first time dm is just to inform the user that the feature exists. Also the `set` command is a core command so that should probably be reported as a issue on the [`main repo`](https://github.com/cog-Creators/Red-DiscordBot)

**Comment by Artemis6969** [comment]
mb. Guess I'll close this
