### ISSUE TITLE
[giveaways] Bots getting rate limit!!

### ISSUE THREAD

**Issue by Cool-aid-man** [i-am-zaidali/cray-cogs#32]
### Giveaway Cog
Hey cray! Bots are getting `rate limit` and getting `quarantined` when the cog is in use in front of just 50 people. I've reported about this issue earlier in the [red support server](https://discord.com/channels/240154543684321280/240212783503900673/983025751995609138). This is getting awfully bad now, I've had the same issue again. Literally with every gaw.

Upon Further Investigating, I think it's the `reaction spam` that is hitting the limit when lots of people are reacting at the `same` time **without** having the required role to participate in the gaw. And the cog is trying to `remove` each reaction at the **same time**.

#### So could you make the cog `not` remove the reactions even if the user `don't` meet the requirement or, atleast make it, so it removes the reaction after a **`delay`**. And intentionally make the cog slower to **DM**, when lots of people are reacting at the same time!!
I think it'd solve the issue with hitting rate limit.

Thanks

### Giveaway Cog
Currently, the giveaway cog only checks the requirement at the start of the gaw, and not when it ends. 
It'd be really amazing if it checks the requirements at the start **`and`** at the end of a giveaway to make it more `fair`. Since there're certain requirements like `voter` for example that requires the user to vote twice if the gaw duration is more than  12 hours, so having the cog only checks at the start of the gaw gives them a **huge** advantage to win the giveaway.

Would be great if you can add that feature into the giveaway cog.

**Comment by japandotorg** [comment]
For the rate limit/quarantine issue, please turn off react & unreact dm using `[p]gset reactdm false` and `[p]gset unreactdm false`.
Discord quarantines bots whenever they try to mass dm people in a short amount of time!

**Comment by Cool-aid-man** [comment]
> For the rate limit/quarantine issue, please turn off react & unreact dm if you haven't already using `[p]gset reactdm false` and `[p]gset unreactdm false`. Discord quarantines bots whenever they try to mass dm people in a short amount of time!

Hi
It is **off.** And `[p]gset unreactdm false` settings is applicable __only__ if the reaction is being removed by `manager` or someone who has perms. It's not applicable when the bot itself is removing the reactions due to not fulfilling the requirements.
And there's no option to **turn that off** as of now.

And I think it's not just cause of `mass DMing` it's cause of **__removing too many reactions__** without having a cooldown between the operation.
