### ISSUE TITLE
Timer Wont load - No Module Names 'emoji'

### ISSUE THREAD

**Issue by WholeThrower119** [i-am-zaidali/cray-cogs#33]
![image](https://user-images.githubusercontent.com/14766995/184038891-6fb49071-3c62-4421-96f9-44dff99a6306.png)
Above is my console.
For some reason, the timer Wont load, it says it needs a module named emoji.

Any reason for it?
Thanks in advance.

**Comment by i-am-zaidali** [comment]
fixed with [1f3e188](https://github.com/i-am-zaidali/cray-cogs/commit/1f3e188448d665e049545518de94dc1f697eebad)

**Comment by WholeThrower119** [comment]
Nice, you added that i needed  `"requirements": ["emoji==1.6.3"],` in the Info file.

where do i get this requirment?
is it a cog on the RedV3 Site? is it something i get from you?
I cant find a simple package or cog named "Emoji" with that version number.

Thanks in advance!

**Comment by i-am-zaidali** [comment]
When you install the cog, red will automatically isntall this requirement for you. And it's not a cog but a pip package.

**Comment by WholeThrower119** [comment]
Oh,  i just had to remove repo and re-add it and it now works. Sorry about that.

I appreciate it sir. Have a good one and thanks or the cogs!
