### ISSUE TITLE
Bypass role not working

### ISSUE THREAD

**Issue by japandotorg** [i-am-zaidali/cray-cogs#4]
umm for some reason the `,g start <time> <winners> <roleID>;;<roleID>[bypass] PRIZE` is not working like the required role works, there's no error either, all it does is the bot DM's me the role_not_have embed `You don't have the required role to enter this giveaway`
also there's some error loading the cog at times, it says `cannot load cog because gset is already an alias` or something like that in the chat, it loads perfectly at times tho.

**Comment by i-am-zaidali** [comment]
Hey japandotorg! 
For the first part about the bypass role not working, I have identified the issue and will be working to solve it ASAP. 
Secondly, the reload bug stating:
> `command` is already a registered command or alias
This is a known bug in redbot and there is no cog based fix for it. It is known as the "hot reload bug" and you can ask about it in the red support server for more information.

**Comment by i-am-zaidali** [comment]
I'll be closing this issue since it has been fixed. Thanks for reporting it :D
