### ISSUE TITLE
[timer] It'd be great, not to have the `ts` as an alias. 

### ISSUE THREAD

**Issue by Cool-aid-man** [i-am-zaidali/cray-cogs#40]
Hey cray,
Hope you're doing great
> I was just wondering if you could remove one of the **default** alias `ts` from the list of alias, as it's messing up with other cogs that has the cmd already and are more important in a way.
> I think it'd be just as fine to have the cog without the `ts` as a **default** alias, as one can easily add it if they like (through tags), and removing `ts` won't make it any harder either.
> Speaking of which people normally uses the `tset` more.

Thanks
Have a great day!

**Comment by i-am-zaidali** [comment]
you can make a PR for it if u want to. Im pretty busy recently

**Comment by Cool-aid-man** [comment]
Alright
Done.

**Comment by i-am-zaidali** [comment]
#41
