### ISSUE TITLE
[Timer] pagify the end message

### ISSUE THREAD

**Issue by sravan1946** [i-am-zaidali/cray-cogs#42]
The message send by the bot should be pagified if its longer than 2000 characters else the bot will raise an HTTPException.
https://sentry.io/share/issue/7ed60fa3fcb149bc847ced58e8eb7c76/

**Comment by i-am-zaidali** [comment]
I wont have time to fix this until next saturday. If you want, you can make a PR and I'll approve it.

**Comment by sravan1946** [comment]
Even im busy for about 2 months so anyone is free to make PR if wanted

**Comment by i-am-zaidali** [comment]
This has been fixed
