### ISSUE TITLE
[Feature Request] set time/date for giveaways

### ISSUE THREAD

**Issue by MayhemBill** [i-am-zaidali/cray-cogs#5]
Title kind of says it all, I would like to be able to set a time/date for giveaways instead of setting a timer for them.

**Comment by i-am-zaidali** [comment]
If i understand correctly, you want to set a date/time when the giveaway automatically gets started right?
For example:
if its a time, then it gets started everyday on that time
if its a date, it gets executed on that date

**Comment by MayhemBill** [comment]
No I'm looking for an set end time

**Comment by i-am-zaidali** [comment]
Forgot about this, but this has been added in the following commit: d2360050ed38ee97dfa2512e0a906f29282761c5
